import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import Provider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import Bugsnag from '@bugsnag/js'
import BugsnagPerformance from '@bugsnag/browser-performance'
Bugsnag.start({ apiKey: process.env.BUGSNAG_API_KEY! })
BugsnagPerformance.start({ apiKey: process.env.BUGSNAG_API_KEY!})


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider>
      <Provider>
      <body className={inter.variable}>
        
        <Theme accentColor="violet" radius="large">
          <NavBar />
          <main className="p-5">
            {" "}
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
      </Provider>
      </QueryClientProvider>
    </html>
  );
}
